services:
  configurator:
    environment:
      PROJECT_CLONE_URL: https://github.com/chbrown13/labspace-testing

  workspace:
    image: dockersamples/labspace-workspace-python
    environment:
      OLLAMA_HOST: http://ollama:11434

  ollama:
    image: ollama/ollama
    volumes:
      - ollama-models:/root/.ollama

volumes:
  ollama-models:
